### PR TITLE
auto improvements

### PR DESCRIPTION
**Pull request by 6749computers**
see commit message in second commit

### CODE REVIEW

**Comment by ingensargens** [comment]
closes #24 but needs improvement
closes #23

**Review by ingensargens — APPROVED** [review]
- S2 0 5 6 2 still needs work to make it within 15 sec

- S1 0 4 5 and S2 0 5 6 should be consistent on an accurate field with carpet 

I think the updated PPLib background clarifies the numbers but let me know

**Comment by ingensargens** [comment]
One thing to note
- deleted autos within PP do not get removed from the shuffleboard options
See [pathplanner docs](https://pathplanner.dev/pplib-build-an-auto.html#create-a-sendablechooser-with-all-autos-in-project) for more info. There is a rudimentary work around

**Comment by mootw** [comment]
is S2 0 5 6 2 within 15 seconds yet?

**Comment by ingensargens** [comment]
> is S2 0 5 6 2 within 15 seconds yet?

No

**Comment by ingensargens** [comment]
> > is S2 0 5 6 2 within 15 seconds yet?
> 
> No

approximately 18 seconds iirc

**Review by mootw — APPROVED** [review]
lgtm needs testing at event

**Pull request merged**
